### ISSUE TITLE
ModuleNotFoundError: No module named 'client'

### ISSUE THREAD

**Issue by themixray** [magahet/peon#12]
```
Traceback (most recent call last):
  File "D:\Загрузки\peon-master\peon-master\autobot.py", line 3, in <module>
    import peon
  File "D:\Загрузки\peon-master\peon-master\peon\__init__.py", line 1, in <module>
    from client import Client
ModuleNotFoundError: No module named 'client'
```

**Comment by PolarsBear** [comment]
Is your code inside the peon folder?
